brokers:
  - broker1
  - broker2

sensors:
  - topic: topic1
    nb: 3
    broker: broker1
  - topic: topic2
    nb: 3
    broker: broker2

ingestionClients:
  - brokers:
      - brokerId: broker1
        topics: 
          - topic1
    
  - brokers:
      - brokerId: broker2
        topics: 
          - topic2
   




