version: "3.0"
services:
    mini-batch-converter:
        build: "."
        environment: 
            KAFKA_BOOTSTRAP_SERVERS: '192.168.1.12:32812,192.168.1.12:32814'
            MQTT_HOST: broker
            MQTT_PORT: 1883
            EDGE_BROKER_NAME: 'edge_broker_gcp'
            BATCH_POOL_FREQUENCY: 10
        entrypoint: ["python3", "converter.py"]        
