version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    
  ingestionclient:
    build: ./ingestionClient

  param_sensor:
    build: ./sensors
    command: ["java", "-jar", "./sdsensor-0.0.1-SNAPSHOT-jar-with-dependencies.jar", "./mqttcloud.params.json", "./data/bts/param-2017-10-23-12-vn.csv"]
    depends_on:
      - mosquitto
    
  alarm_sensor:
    build: ./sensors
    command: ["java", "-jar", "./sdsensor-0.0.1-SNAPSHOT-jar-with-dependencies.jar", "./mqttcloud.alarms.json", "./data/bts/alarm-2017-10-23-12-vn.csv"]
    depends_on:
      - mosquitto
  
  