---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-inference-server
  labels:
    app: cloud-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-inference-server
  template:
    metadata:
      labels:
        app: cloud-inference-server
    spec:
      restartPolicy: Always
      nodeSelector:
        workerType: "cloudWorker.rdsea.csc"
      containers:
        - name: cloud-inference
          image: rdsea/cloud-ml-inference-server:1.2
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-inference-service
spec:
  ports:
  - port: 4001
    targetPort: 4000
    nodePort: 30000
  selector:
    app: cloud-inference-server
  type: NodePort