# @framework: SEAFramework
# @sub-system: edge
# @type: broker
version: "3.7"
services:
  vmq-main:
    image: vernemq/vernemq
    ports:
      - 1883:1883
      - 8888:8888
    environment:
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
  vmq-secondary:
    image: vernemq/vernemq
    environment:
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_DISCOVERY_NODE=vmq-main"
  broker_log_writer:
    build: "./EdgeBrokerLogger/"
    depends_on: 
      - vmq-main
    volumes:
      - "./logs/subscription logs/:/logger/log"
    entrypoint: ["python3", "mqtt_client.py", "broker", "1883"]

